name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Build Docker image
        run: docker build . -t luissoto25/mi-app:${{ github.sha }}

      - name: Log in to Docker Hub
        run: docker login -u luissoto25 -p Mathias2024$$ https://github.com/lsoto25/Dev.git

      - name: Push Docker image
        run: docker push luissoto25/mi-app:${{ github.sha }}

      - name: Update Kubernetes manifests
        run: |
          sed -i 's|image: .*|image: luissoto25/mi-app:${{ github.sha }}|' k8/deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Updated image to ${{ github.sha }} [ci-skip]"
          git push origin main